# .pre-commit-config.yaml
exclude: ^(\.venv/|venv/|backend/\.venv/)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: ^backend/
        exclude: ^(backend/\.venv/|\.venv/|venv/)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^backend/
        exclude: ^(backend/\.venv/|\.venv/|venv/)
