# .ruff.toml
line-length = 88
target-version = "py312"

[lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
