# Ruff configuration
line-length = 88
target-version = "py312"

[lint]
select = ["E", "F", "I"]   # Errors, formatting, import rules
ignore = ["E501"]          # Disable long line warning (Black handles it)

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
