"""create users

Revision ID: 81d9ea116edd
Revises: 4f283aabddc2
Create Date: 2025-09-21 19:44:34.810180

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "81d9ea116edd"
down_revision: Union[str, Sequence[str], None] = "4f283aabddc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
