"""create external_users

Revision ID: ec485fba6774
Revises: 4cdb56e06fd9
Create Date: 2025-09-21 23:44:41.609714

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ec485fba6774"
down_revision: Union[str, Sequence[str], None] = "4cdb56e06fd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
