# compose/prometheus.yml
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'etl-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
